architect: true
watch-files: true
max-chat-history-tokens: "8192"
restore-chat-history: false
read:
  - docker-compose.yml
  - .env.example

file:
  - config/bookmarks.yaml
  - config/docker.yaml
  - config/services.yaml
  - config/settings.yaml

auto-commits: false
attribute-commit-message-author: true

map-tokens: "2048"
map-refresh: always

editor: neovim