---
name: homepage
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 100.71.85.25:81:3000
    volumes:
      - config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.scope=global"
    restart: always
volumes:
  config:
    driver: local
    driver_opts:
      type: none
      device: ./config
      o: bind
