---
- infrastructure:
  - Tailscale:
    - abbr: TS
      href: https://login.tailscale.com/admin/machines
  - Proxmox:
    - abbr: PVE
      href: https://pve-1.bun-delta.ts.net:8006
  - unraid:
      href: http://unraid.bun-delta.ts.net