---
Cloud-Main:
    socket: /var/run/docker.sock
DL380:
    host: dl380.bun-delta.ts.net
    port: 2375
Unraid:
    host: unraid.bun-delta.ts.net
    port: 2375
Polar-1:
    host: polar-1.bun-delta.ts.net
    port: 2375
Chungus:
    host: chungus.bun-delta.ts.net
    port: 2375
