Hetzner-Main:
    socket: /var/run/docker.sock
Docker-GPU:
    host: docker-gpu.bun-delta.ts.net
    port: 2375
Unraid:
    host: unraid.bun-delta.ts.net
    port: 2375
Oracle-DB:
    host: oracle-db.bun-delta.ts.net
    port: 2375