---
Cloud-Main:
    socket: /var/run/docker.sock
Docker-GPU:
    host: docker-gpu.bun-delta.ts.net
    port: 2375
Unraid:
    host: unraid.bun-delta.ts.net
    port: 2375
Polar-1:
    host: polar-1.bun-delta.ts.net
    port: 2375