---
headerStyle: boxed
theme: dark
useEqualHeights: true
fiveColumns: true
layout:
    Media:
        style: row
        columns: 4
    AI + Automation + Monitoring:
        initiallyCollapsed: true
        style: row
        columns: 4
    Cloud-Main:
        initiallyCollapsed: true
        style: row
        columns: 4
